#!/usr/bin/env python3
'''
Generate figures summarizing the results of experiment 1.
'''
from json import loads
from os import makedirs

import matplotlib.pyplot as plt
import seaborn as sbn

################################################################################
# Load the experiment result.
################################################################################

with open('nets/experiment-1.json', 'r') as f:
    log = loads(f.read())

################################################################################
# Create a directory in which to store figures.
################################################################################

makedirs('figures/experiment-1/', exist_ok=True)

################################################################################
# Generate figures.
################################################################################

sr_acc = [log['sr']['acc_ts']]
sr_moc = [log['sr']['moc_ts']]
dr_acc = [entry['net']['acc_ts'] for entry in log['dr']]
dr_moc = [entry['net']['moc_ts'] for entry in log['dr']]

plt.rc('text', usetex=True)
plt.figure(figsize=(4, 3))
sbn.set_style('ticks')
plt.xlabel('Mean Op Count')
plt.xticks([0, 2e6, 4e6, 6e6])
plt.ticklabel_format(axis='x', style='sci', scilimits=(0, 0))
plt.ylabel('Accuracy')
plt.ylim([0.9, 1])
plt.scatter(sr_moc, sr_acc, color='r', label='Static routing')
plt.scatter(dr_moc, dr_acc, label='Dynamic routing')
plt.legend(loc='lower right', fontsize=8)
sbn.despine()
plt.tight_layout()
plt.savefig('figures/experiment-1/sat.pdf')
