#!/usr/bin/env python3
'''
Train statically-routed networks.
'''
from os import makedirs

import numpy as np
import tensorflow as tf

from lib.data import Dataset
from lib.nets import sr_chain, tf_specs
from lib.training import train

################################################################################
# Load and preprocess data.
################################################################################

m_cls = [0, 0, 1, 1, 1, 1, 1, 1, 0, 0]
w_cls = np.transpose([np.equal(m_cls, i) for i in range(2)])

dataset = Dataset('data/cifar-10.mat')
dataset.y_tr = np.dot(dataset.y_tr, w_cls)
dataset.y_ts = np.dot(dataset.y_ts, w_cls)

################################################################################
# Define training hyperparameters.
################################################################################

n_epochs = 40
λ_learn = 0.1
μ_learn = 0.9
t_anneal = 10

################################################################################
# Train networks.
################################################################################

for n_tf in range(len(tf_specs) + 1):
    with tf.Graph().as_default():
        t_train = tf.placeholder(tf.float32, ())
        optimizer = tf.train.MomentumOptimizer(
            λ_learn / 10**(t_train // t_anneal), μ_learn)
        net = sr_chain(n_tf, optimizer)
        train(net, dataset, n_epochs=n_epochs,
              name=('SRNet (n_tf=%i)' % n_tf),
              hypers=(lambda t: {t_train: t}))
        makedirs('nets/sr-chains', exist_ok=True)
        net.write('nets/sr-chains/net%i.tfn' % n_tf)
